services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
