services:
  app:
    image: node:18-alpine
    restart: always
    command:
      - sh
      - -c
      - |
        if(([ ! -e posted-alerts.json ])) then (echo [] >> posted-alerts.json) fi
        yarn install && yarn start
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
